In [2]:
# import
import numpy as np
import numpy.linalg as LA


1. Matrix Operation

In [3]:
A = np.array([[2, -1], [0, 3]])
B= np.array([[1, 2], [-3, 4]])

# A + B
add_result = A + B

# AB
mul_result = A @ B

# 3A - 2B
exp_result = 3*A - 2*B

#print the results
print("A + B:\n", add_result)
print("\nAB:\n", mul_result)
print("\n3A - 2B:\n", exp_result)


A + B:
 [[ 3  1]
 [-3  7]]

AB:
 [[ 5  0]
 [-9 12]]

3A - 2B:
 [[ 4 -7]
 [ 6  1]]


The program adds two square matrices element-wise, producing a new matrix where each element is the sum of the corresponding elements from the input matrices


2. Determinants and Inverses

In [5]:
# Determinant of A
det_A = LA.det(A)
print("Determinant of A:", det_A)

if det_A != 0:
    inv_A = LA.inv(A)
    print("Matrix A is invertible and")
    print("\nInverse of A:\n", inv_A)
else:
    print("\nMatrix A is not invertible")

Determinant of A: 6.0
Matrix A is invertible and

Inverse of A:
 [[0.5        0.16666667]
 [0.         0.33333333]]


Determinant of a mateic is a single number calculated from a suare matrix that shows whether the matrix is invertible ; if determinant is sero ,inverse doesnot exist

Since the determinant of A isn't equal to zero (det(A) = 6), the matrix A is invertible.


3. Eigen Values and Eigen Vectors

In [6]:

C = np.array([[4, 1],
              [-2, 1]])
#print the matrix
print('Matrix A:\n', A)
eigenvalues, eigenvectors = LA.eig(A)

#print the results
print("\nEigenvalue:")
print(eigenvalues[0], eigenvalues[1])
print("\nCorresponding Eigenvector:")
print(eigenvectors)

Matrix A:
 [[ 2 -1]
 [ 0  3]]

Eigenvalue:
2.0 3.0

Corresponding Eigenvector:
[[ 1.         -0.70710678]
 [ 0.          0.70710678]]


Eigenvalues are special numbers that show how a matrix scales a vector, Eigenvectors are non-zero vectors whose direction doesnot change after matrix multiplication .

Here, the eigenvalues are: 2 and 3

4. Car Price Prediction

In [7]:
#x1 x2 x3 price
x = np.array([[4, 1.5, 100],
                [6, 2.0, 150]])

#price vector
y = np.array([20, 30])

x_transpose = x.T
beta = LA.pinv(x_transpose @ x) @ x_transpose @ y

print('\n Coefficient vector(beta):\n', beta)

#predict price for third car
x_new = np.array([8, 3.0, 200])
predicted_price = x_new @ beta

print("\nPredicted price of car 3:", predicted_price)


 Coefficient vector(beta):
 [ 7.98722045e-03 -4.12114787e-13  1.99680511e-01]

Predicted price of car 3: 39.99999999999998


So, the predicted price of car 3 is: 39.99"